controllers:
    resource: ../src/Controller/
    type: annotation
article_details:
    path: /article/{id}
    controller: 'App\Controller\IndexController::details'

articles:
    path: /articles
    controller: App\Controller\IndexController::showArticles
